server:
  port: 8081

spring:
  application:
    name: easywork-console
  profiles:
    active: dev
  
  # 数据库配置
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST}:3306/easywork?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: ${MYSQL_PASSWORD}
      # 连接池配置
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        auto-commit: true
        idle-timeout: 30000
        pool-name: EasyworkHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1

  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  # 国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  
  # OAuth2配置
  security:
    oauth2:
      client:
        registration:
          demo-client:
            client-id: client
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
        provider:
          demo-client:
            authorization-uri: http://127.0.0.1:9002/oauth2/authorize
            token-uri: http://127.0.0.1:9002/oauth2/token
            user-info-uri: http://127.0.0.1:9002/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://127.0.0.1:9002/oauth2/jwks


# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.easywork.console.infra.repository.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.easywork.console.trigger.http.controller

# 日志配置
logging:
  level:
    org.springframework.security: DEBUG
    org.easywork.console: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 自定义配置
easywork:
  # JWT配置
  jwt:
    secret: easywork-secret-key-for-jwt-token-generation
    expiration: 86400000 # 24小时
    
  # 文件上传配置
  file:
    upload-path: /tmp/easywork/uploads
    max-size: 100MB
    allowed-types: jpg,jpeg,png,gif,bmp,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar
    
  # 代码生成器配置
  generator:
    author: easywork
    package-name: org.easywork.console
    table-prefix: t_

